apiVersion: v1
kind: PersistentVolume
metadata:
  name: starrocks-fe-pv
spec:
  storageClassName: standard        # 必须与 PVC 完全一致
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/starrocks/fe        # 宿主机真实路径
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: starrocks-fe-pvc
  namespace: bigdata
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: starrocks-fe-pv   # 强制绑定 PV
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: starrocks-cn-data-pv
spec:
  storageClassName: standard
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/starrocks/cn/storage
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: starrocks-cn-data-pvc
  namespace: bigdata
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: starrocks-cn-data-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: starrocks-be-data-pv
spec:
  storageClassName: standard
  capacity:
    storage: 100Gi          # 学习版不用 1Ti，留点磁盘给自己
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/starrocks/be/storage
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: starrocks-be-data-pvc
  namespace: bigdata
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: starrocks-be-data-pv
