apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink-app-role
  namespace: flink
rules:
- apiGroups: [""]
  resources:
    - services
    - pods
    - configmaps
  verbs:
    - get
    - list
    - watch
    - create
    - delete
- apiGroups: ["apps"]
  resources:
    - deployments
  verbs:
    - get
    - list
    - watch
    - create
    - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-app-rb
  namespace: flink
subjects:
- kind: ServiceAccount
  name: flink
  namespace: flink
roleRef:
  kind: Role
  name: flink-app-role
  apiGroup: rbac.authorization.k8s.io
